// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQuNV2C5P3Xj4VK8bekZnaJWeVo1Nspu0',
    appId: '1:508167360591:web:fc6d9700cd50cf08d01a3a',
    messagingSenderId: '508167360591',
    projectId: 'uber-ola-and-indriver-cl-f6cf4',
    authDomain: 'uber-ola-and-indriver-cl-f6cf4.firebaseapp.com',
    databaseURL: 'https://uber-ola-and-indriver-cl-f6cf4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-cl-f6cf4.appspot.com',
    measurementId: 'G-T9MLNKT9WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdNKsJLNPnZkQO7ht-fhKViPMxICVMLA',
    appId: '1:508167360591:android:b7971a5d900a9fd7d01a3a',
    messagingSenderId: '508167360591',
    projectId: 'uber-ola-and-indriver-cl-f6cf4',
    databaseURL: 'https://uber-ola-and-indriver-cl-f6cf4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-cl-f6cf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDelbXEeVxlXIPCEeBemHkxfhyZJyYKEqk',
    appId: '1:508167360591:ios:978932c5d3e86a3fd01a3a',
    messagingSenderId: '508167360591',
    projectId: 'uber-ola-and-indriver-cl-f6cf4',
    databaseURL: 'https://uber-ola-and-indriver-cl-f6cf4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-cl-f6cf4.appspot.com',
    iosClientId: '508167360591-dopn64s6evebdorp2u1jcoju9n5am4mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberUsersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDelbXEeVxlXIPCEeBemHkxfhyZJyYKEqk',
    appId: '1:508167360591:ios:978932c5d3e86a3fd01a3a',
    messagingSenderId: '508167360591',
    projectId: 'uber-ola-and-indriver-cl-f6cf4',
    databaseURL: 'https://uber-ola-and-indriver-cl-f6cf4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-ola-and-indriver-cl-f6cf4.appspot.com',
    iosClientId: '508167360591-dopn64s6evebdorp2u1jcoju9n5am4mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.uberUsersApp',
  );
}
